package com.github.ozzymar.talismansmega.items;

public class NBT_KEYS {
    public String IS_FLASH_TALISMAN = "IS_FLASH_TALISMAN";
    public String IS_HEALTH_TALISMAN = "IS_HEALTH_TALISMAN";
    public String IS_WARRIOR_TALISMAN = "IS_WARRIOR_TALISMAN";
    public String IS_IRONSKIN_TALISMAN = "IS_IRONSKIN_TALISMAN";
    public String IS_QUICKHANDS_TALISMAN = "IS_QUICKHANDS_TALISMAN";
    public String IS_MOLTENSKIN_TALISMAN = "IS_MOLTENSKIN_TALISMAN";
    public String IS_WATERBREATH_TALISMAN = "IS_WATERBREATH_TALISMAN";
    public String IS_WORKBENCH_TALISMAN = "IS_WORKBENCH_TALISMAN";
    public String IS_ENDER_TALISMAN = "IS_ENDERCHEST_TALISMAN";

    public String IS_TALISMAN = "THIS_ITEM_IS_A_TALISMAN";

    public String TALISMAN_UUID = "UUID";
}
